### ISSUE TITLE
Commands appear outdated

### ISSUE THREAD

**Issue by mortonjt** [knightlab-analyses/empress-analyses#15]
It looks like the empress commands are outdated.  There was a `community-plot` command that no longer exists in the current API.

https://github.com/knightlab-analyses/empress-analyses/blob/master/notebooks/fig1.ipynb

**Comment by fedarko** [comment]
I think it's the other way around -- we split `plot` into `community-plot` and `tree-plot` about a month ago (https://github.com/biocore/empress/pull/375). The version of Empress you have installed may be out-of-date.

**Comment by mortonjt** [comment]
weird ... I see that now.

**Comment by fedarko** [comment]
Cool, sorry for the confusion. One related thing I should mention, if it would help interpretation for the ILR stuff we could probably also set up an additional Empress command for visualizing ILRs specifically (without too much effort) -- I don't know if e.g. changing the Emperor axis labels or some of the Empress UI elements would make interpretation easier for users, but if so that would be very doable :)

**Comment by mortonjt** [comment]
@fedarko let's first get the bare components in and then we can think about expanding it out.

Regarding the ordination issue -- it turns out to go way back to skbio.  There is no information in skbio that actually keeps track of the PC labels :(
The hack around this is to fake biplot arrows -- here is an example of this
```
Eigvals 6
0.3514131018479627      0.13017133231385764     0.08349820747863729     0.07753041641906193     0.016930002575034218    0.00027341533273661777

Proportion explained    6
0.025658653870706774    0.19728414954025902     0.12654762425601604     0.0004143808811924424   0.5325921898703597      0.11750300158146613

Species 6       6
y775    1.0     0.0     0.0     0.0     0.0     0.0
y900    0.0     1.0     0.0     0.0     0.0     0.0
y678    0.0     0.0     1.0     0.0     0.0     0.0
y766    0.0     0.0     0.0     1.0     0.0     0.0
y10     0.0     0.0     0.0     0.0     1.0     0.0
y297    0.0     0.0     0.0     0.0     0.0     1.0

Site    154     6
11212.Asen1019  0.0     0.0     0.0     0.0     0.20299422533803038     0.0
11212.RT2013    0.0     0.0     0.0     0.0     0.0     -0.47356896707699836
11212.ERUB.12M  0.0     0.0     0.0     0.0     -1.095999048157671      0.0
```
